[project]
name = "mcp-course"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.116.1",
    "fastmcp>=2.12.2",
    "ipykernel>=6.29.5",
    "langchain>=0.3.25",
    "langchain-core>=1.2.5",
    "langchain-mcp-adapters>=0.1.1",
    "langchain-openai>=0.3.17",
    "langchain-google-genai>=4.1.2",
    "langgraph>=0.4.5",
    "python-jose>=3.4.0",
    "ruff>=0.11.10",
    "uvicorn>=0.34.2",
]
